package com.solarvillage.rhpam.poc.datamodal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public NewOrder() {
    }




}