package com.solarvillage.rhpam.poc.datamodal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("orderID")
	private java.lang.String orderID;
	@org.kie.api.definition.type.Label(value = "electricalPermit")
	private com.solarvillage.rhpam.poc.datamodal.ProjectPermit electricalPermit;

	@org.kie.api.definition.type.Label(value = "structuralPermit")
	private com.solarvillage.rhpam.poc.datamodal.ProjectPermit structuralPermit;

	@org.kie.api.definition.type.Label(value = "customer")
	private com.solarvillage.rhpam.poc.datamodal.Customer customer;

	@org.kie.api.definition.type.Label(value = "hoaAddress")
	private com.solarvillage.rhpam.poc.datamodal.Address hoaAddress;

	@org.kie.api.definition.type.Label(value = "hoaApproval")
	private com.solarvillage.rhpam.poc.datamodal.ProjectPermit hoaApproval;

	public NewOrder() {
	}

	public java.lang.String getOrderID() {
		return this.orderID;
	}

	public void setOrderID(java.lang.String orderID) {
		this.orderID = orderID;
	}

	public com.solarvillage.rhpam.poc.datamodal.ProjectPermit getElectricalPermit() {
		return this.electricalPermit;
	}

	public void setElectricalPermit(
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit electricalPermit) {
		this.electricalPermit = electricalPermit;
	}

	public com.solarvillage.rhpam.poc.datamodal.ProjectPermit getStructuralPermit() {
		return this.structuralPermit;
	}

	public void setStructuralPermit(
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit structuralPermit) {
		this.structuralPermit = structuralPermit;
	}

	public com.solarvillage.rhpam.poc.datamodal.Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(
			com.solarvillage.rhpam.poc.datamodal.Customer customer) {
		this.customer = customer;
	}

	public com.solarvillage.rhpam.poc.datamodal.Address getHoaAddress() {
		return this.hoaAddress;
	}

	public void setHoaAddress(
			com.solarvillage.rhpam.poc.datamodal.Address hoaAddress) {
		this.hoaAddress = hoaAddress;
	}

	public com.solarvillage.rhpam.poc.datamodal.ProjectPermit getHoaApproval() {
		return this.hoaApproval;
	}

	public void setHoaApproval(
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit hoaApproval) {
		this.hoaApproval = hoaApproval;
	}

	public NewOrder(
			java.lang.String orderID,
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit electricalPermit,
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit structuralPermit,
			com.solarvillage.rhpam.poc.datamodal.Customer customer,
			com.solarvillage.rhpam.poc.datamodal.Address hoaAddress,
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit hoaApproval) {
		this.orderID = orderID;
		this.electricalPermit = electricalPermit;
		this.structuralPermit = structuralPermit;
		this.customer = customer;
		this.hoaAddress = hoaAddress;
		this.hoaApproval = hoaApproval;
	}
	
		public NewOrder(
			com.solarvillage.rhpam.poc.datamodal.Customer customer,
			com.solarvillage.rhpam.poc.datamodal.Address hoaAddress,
			com.solarvillage.rhpam.poc.datamodal.ProjectPermit hoaApproval) {
		this.orderID = String.valueOf(System.currentTimeMillis());
		this.electricalPermit = new com.solarvillage.rhpam.poc.datamodal.ProjectPermit();
		this.structuralPermit = new com.solarvillage.rhpam.poc.datamodal.ProjectPermit();
		this.customer = customer;
		this.hoaAddress = hoaAddress;
		this.hoaApproval = hoaApproval;
	}

}